name: Rust CI

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: thomasmarches/allfeat-chain:1.0

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Check code formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

    - name: Lint with clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests in examples
      run: |
        chmod +x ./test-all-examples.sh
        ./test-all-examples.sh
